import styles from './AvailableModels.module.scss';
import { Config } from '../../config';


export const AvailableModels = () => {

    return <div className={`global-padding ${styles['available-models']}`} id='available-tasks'>
        <div className={`d-flex align-items-center justify-content-between ${styles['section-header']} mb-5`}>
            <h2>Available Tasks</h2>
        </div>
        <div className='row'>
            <div className='table-responsive'>
                <table className='table custom-table'>
                    <thead>
                        <tr>
                            <th>Model</th>
                            <th>Description</th>
                            <th>Endpoint</th>
                            <th>Link</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Guardrail</td>
                            <td>Flags unsafe or harmful messages sent by user or generated by an LLM</td>
                            <td><a 
                                href={Config.GUARDRAIL_HF_LINK}
                                target='_blank' rel='noreferrer'
                            >
                                tanaos/tanaos-guardrail-v1
                            </a>
                            </td>
                            <td>Try it out</td>
                        </tr>
                        <tr>
                            <td>Intent Classification</td>
                            <td>Classifies user messages into predefined intent categories.</td>
                            <td>
                                <a 
                                    href={Config.INTENT_CLASSIFICATION_HF_LINK}
                                    target='_blank' rel='noreferrer'
                                >
                                    tanaos/tanaos-intent-classifier-v1
                                </a>
                            </td>
                            <td>Try it out</td>
                        </tr>
                        <tr>
                            <td>Reranker</td>
                            <td>Ranks a list of items or search results based on relevance to a query.</td>
                            <td>
                                <a 
                                    href={Config.RERANKER_HF_LINK}
                                    target='_blank' rel='noreferrer'
                                >
                                    cross-encoder/mmarco-mMiniLMv2-L12-H384-v1
                                </a>
                            </td>
                            <td>Try it out</td>
                        </tr>
                        <tr>
                            <td>Sentiment Analysis</td>
                            <td>Determines the sentiment (positive, negative, neutral) of a given text.</td>
                            <td>
                                <a 
                                    href={Config.SENTIMENT_ANALYSIS_HF_LINK}
                                    target='_blank' rel='noreferrer'
                                >
                                    tanaos/tanaos-sentiment-analysis-v1
                                </a>
                            </td>
                            <td>Try it out</td>
                        </tr>
                        <tr>
                            <td>Emotion Detection</td>
                            <td>Identifies the emotion expressed in a given text.</td>
                            <td>
                                <a 
                                    href={Config.EMOTION_DETECTION_HF_LINK}
                                    target='_blank' rel='noreferrer'
                                >
                                    tanaos/tanaos-emotion-detection-v1
                                </a>
                            </td>
                            <td>Try it out</td>
                        </tr>
                        <tr>
                            <td>Named Entity Recognition</td>
                            <td>Detects and classifies named entities in text.</td>
                            <td>
                                <a 
                                    href={Config.NER_HF_LINK}
                                    target='_blank' rel='noreferrer'
                                >
                                    tanaos/tanaos-NER-v1
                                </a>
                            </td>
                            <td>Try it out</td>
                        </tr>
                        <tr>
                            <td>Text Anonymization</td>
                            <td>Removes personally identifiable information (PII) from text.</td>
                            <td>
                                <a 
                                    href={Config.TEXT_ANONYMIZATION_HF_LINK}
                                    target='_blank' rel='noreferrer'
                                >
                                    tanaos/tanaos-text-anonymizer-v1
                                </a>
                            </td>
                            <td>Try it out</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
};

export default AvailableModels;