import React from 'react';

import './index.scss';
import { Config } from '../../../config';


export const WhyTanaosSection = () => {

    const TryItNowLink = () => {
        return <a href={Config.SYNTHEX_GITHUB_URL} target='_blank' rel='noopener'>Try it now ➔</a>
    };

    return <div id='why-tanaos' className='why-tanaos-section global-padding'>
        <div className='row mb-4'>
            <h2 className='mb-5'>Why Tanaos?</h2>
            <div className='col-12 col-md-8'>
                <p>
                    Finding large, high-quality, private and GDPR-compliant datasets on the Internet is difficult.
                    Even if you do find them, they rarely have all the characteristics you need. Tanaos takes a 
                    different approach to data gathering, allowing you to generate your own datasets by specifying 
                    the characteristics they should have. The output data is virtually undistinguishable from real data,
                    while maintaining high standards of privacy and anonymity.
                </p>
            </div>
        </div>
        <div className='row mt-5'>
            <div className='col-12 col-md-4 pe-md-5'>
                <div className='icon-container mb-5'>
                    <i className='bi bi-stopwatch'></i>
                </div>
                <h5>Reduce times</h5>
                <p className='mt-3'>
                    Tired of waisting time looking for the right dataset on the internet? 
                    Tanaos allows you to generate custom, large and accurate datasets in minutes, whatever your 
                    use-case may be.
                </p>
                <TryItNowLink />
            </div>
            <div className='col-12 col-md-4 pe-md-5 mt-5 mt-md-0'>
                <div className='icon-container mb-5'>
                    <i className='bi bi-graph-up-arrow'></i>
                </div>
                <h5>Increase productivity</h5>
                <p className='mt-3'>
                    Your and your team's productivity heavily depends on the quality of the data you use. 
                    Increase your app and team's performance by generating high-quality data customized for
                    your use-case.
                </p>
                <TryItNowLink />
            </div>
            <div className='col-12 col-md-4 pe-md-5 mt-5 mt-md-0'>
                <div className='icon-container mb-5'>
                    <i className='bi bi-lock-fill'></i>
                </div>
                <h5>Be GDPR-compliant</h5>
                <p className='mt-3'>
                    Worried about whether the datasets you use are legal under EU regulations? We got you covered:
                    the data generated by our tools is 100% private, anonymized and GDPR-compliant.
                </p>
                <TryItNowLink />
            </div>
        </div>
    </div>
};

export default WhyTanaosSection;